# Generated by Django 3.2.8 on 2025-03-28 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_news_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='alt',
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 7, 38, 0, 477541), verbose_name='Время публикации'),
        ),
    ]
