# Generated by Django 3.2.8 on 2025-03-28 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20250328_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Перевод(Описание SEO)'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тайтл SEO'),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Перевод(Тайтл SEO)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 8, 53, 22, 94244), verbose_name='Время публикации'),
        ),
    ]
