# Generated by Django 3.2.8 on 2025-03-29 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20250328_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 8, 18, 43, 952224), verbose_name='Время публикации'),
        ),
    ]
