# Generated by Django 3.2.8 on 2023-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateapp', models.DateTimeField(auto_now=True, verbose_name='Дата поступления')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип заявки')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Обращение')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('file', models.FileField(blank=True, null=True, upload_to='crm/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Заявка-обращение',
                'verbose_name_plural': 'Заявки-обращения',
            },
        ),
    ]
