# Generated by Django 3.2.8 on 2023-10-30 08:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product/files/filters', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория фильтра',
                'verbose_name_plural': 'Категории фильтров',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование продукта для работы')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(upload_to='product/files/items', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг alt')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты для работы',
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование пакета')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(upload_to='product/files/packet', verbose_name='Изображение')),
                ('drawing', models.ImageField(upload_to='product/files/packet/drawing', verbose_name='Чертеж')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг alt')),
            ],
            options={
                'verbose_name': 'Пакет',
                'verbose_name_plural': 'Пакеты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Наименование товара')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод наименования')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание товара')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Перевод')),
                ('clients', models.ManyToManyField(blank=True, null=True, related_name='Product', to='content.Client', verbose_name='Клиенты купившие товар')),
                ('equipments', models.ManyToManyField(blank=True, null=True, related_name='Equipment', to='product.Product', verbose_name='Доп оборудование')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование характеристики')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование решения')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(upload_to='product/files/solution', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг alt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solution', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Готовое решение',
                'verbose_name_plural': 'Готовые решения',
            },
        ),
        migrations.CreateModel(
            name='SliderProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='product/files/slider', verbose_name='Изображение')),
                ('alt', models.CharField(max_length=100, null=True, verbose_name='Тэг alt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SliderProd', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Слайдер товара',
                'verbose_name_plural': 'Слайдеры товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000, null=True, verbose_name='Значение характеристики')),
                ('name_en', models.TextField(max_length=1000, null=True, verbose_name='Перевод')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductPropertyValue', to='product.product')),
                ('product_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PropertyValue', to='product.productproperties', verbose_name='Харакартеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
            },
        ),
        migrations.AddField(
            model_name='productproperties',
            name='product',
            field=models.ManyToManyField(related_name='ProductProperties', through='product.ProductPropertyValue', to='product.Product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='PacketSeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип шва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(upload_to='product/files/packet/seam', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг alt')),
                ('packet', models.ManyToManyField(related_name='Seam', to='product.Packet', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Тип шва',
                'verbose_name_plural': 'Типы швов',
            },
        ),
        migrations.CreateModel(
            name='PacketOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Опции пакета')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(upload_to='product/files/packet/options', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг alt')),
                ('packet', models.ManyToManyField(related_name='Options', to='product.Packet', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Опция пакета',
                'verbose_name_plural': 'Опции пакетов',
            },
        ),
        migrations.AddField(
            model_name='packet',
            name='product',
            field=models.ManyToManyField(related_name='Packet', to='product.Product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='ItemsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование примера продукта')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('img', models.ImageField(upload_to='product/files/items_example', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тэг alt')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemsExample', to='product.items', verbose_name='Примеры продуктов')),
            ],
            options={
                'verbose_name': 'Пример продукта',
                'verbose_name_plural': 'Примеры продуктов',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='Items', to='product.Product'),
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Наименование фильтра')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Перевод')),
                ('search', models.CharField(max_length=100, null=True, verbose_name='Поисковый запрос')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Filters', to='product.categoryfilters', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование документа')),
                ('file', models.FileField(null=True, upload_to='product/files/docs', verbose_name='Документация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Docs', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
