# Generated by Django 3.2.8 on 2023-10-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetoptions',
            name='product',
            field=models.ManyToManyField(related_name='PacketsOptions', to='product.Product', verbose_name='Продукт'),
        ),
    ]
