# Generated by Django 3.2.8 on 2024-02-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Не отображать в раскрое'),
        ),
    ]
