# Generated by Django 3.2.8 on 2024-07-20 13:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_packet_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Отображать в раскрое'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Значение характеристики'),
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='name_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Перевод'),
        ),
    ]
