# Generated by Django 3.2.8 on 2024-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20240720_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product/files/filter', verbose_name='Изображение'),
        ),
    ]
