# Generated by Django 3.2.8 on 2025-03-28 08:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20250328_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='filters',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Перевод(Описание SEO)'),
        ),
        migrations.AddField(
            model_name='filters',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тайтл SEO'),
        ),
        migrations.AddField(
            model_name='filters',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Перевод(Тайтл SEO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Перевод(Описание SEO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Тайтл SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Перевод(Тайтл SEO)'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Перевод(Описание товара)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Перевод(Наименование товара)'),
        ),
    ]
