# Generated by Django 3.2.8 on 2025-03-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20250328_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filters',
            options={'verbose_name': 'Фильтр(Категория)', 'verbose_name_plural': 'Фильтры(Категории)'},
        ),
        migrations.AddField(
            model_name='product',
            name='category_filters',
            field=models.ManyToManyField(blank=True, null=True, related_name='Product', to='product.Filters', verbose_name='Фильтры(Категории)'),
        ),
    ]
